docs/DeveloperGuide.md

- Update target user profile and value proposition
- update user stories
- Add in update Dentist use case 
- Update glossary
- Update non-functional requirements

DG updates

---

docs/DeveloperGuide.md
docs/UserGuide.md

Make changes to Add Dentist use case

Update use cases for Search Dentist, Delete Dentist. 

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddPatientCommand.java
src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/ReadOnlyAddressBook.java
src/main/java/seedu/address/model/person/AppointmentDate.java
src/main/java/seedu/address/model/person/Appointmentdate.java
src/main/java/seedu/address/model/person/Birthdate.java
src/main/java/seedu/address/model/person/Gender.java
src/main/java/seedu/address/model/person/Service.java
src/main/java/seedu/address/model/person/UniquePatientList.java
src/main/java/seedu/address/model/person/patients/Patient.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPatient.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/PatientCard.java
src/main/java/seedu/address/ui/PatientListPanel.java
src/main/resources/view/MainWindow.fxml
src/main/resources/view/PatientListCard.fxml
src/main/resources/view/PatientListPanel.fxml
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/model/AddressBookTest.java

- only basic features are implemented:
- user enters a command -> gets stored in model + storage -> changed are updated in gui
TODO:
- Add in test cases for more fields
- Add in checks for fields eg gender, appointment etc
- JavaDoc cleanup
Testing:
- remember to delete `addressbook.json` before running this version.

Add patient Command

---

src/main/java/seedu/address/storage/JsonSerializableAddressBook.java

original steps to reproduce error:
1. delete data/addressbook.json
2. open application
3. exit application
4. open application again. 
(unable to load json file. Blank json file would be produced)

Critical bug fix: Fix bug whereby reloading application results in failure to load json

---

src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/ReadOnlyAddressBook.java
src/main/java/seedu/address/model/person/patients/Patient.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPatient.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
src/main/java/seedu/address/ui/PatientCard.java
src/main/resources/view/PatientListCard.fxml
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/model/AddressBookTest.java

- Addressbook.json must be deleted first before running ToothTracker
- Each new patient would be assigned a new unique index
- Addressbook now stores patient index count

Add in unique patient ID indexing

---

src/main/java/seedu/address/logic/commands/DeleteDentistCommand.java
src/main/java/seedu/address/logic/commands/DeletePatientCommand.java
src/main/java/seedu/address/logic/commands/ListDentistsCommand.java
src/main/java/seedu/address/logic/commands/SearchPatientCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java

`list-dentists` command implemented.

List dentist command

---

src/main/java/seedu/address/logic/commands/ListPatientCommand.java
src/main/java/seedu/address/logic/commands/SearchPatientCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/SearchPatientCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/PatientNameContainsKeywordsPredicate.java
src/main/java/seedu/address/ui/PatientCard.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java

Add in list-patients feature

---

src/main/java/seedu/address/logic/commands/SearchDentistCommand.java
src/main/java/seedu/address/logic/commands/SearchPatientCommand.java
src/main/java/seedu/address/logic/parser/SearchPatientCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java

to support searching by patient ID. Update search dentist bug fix

Add patient search

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/DeleteDentistCommand.java
src/main/java/seedu/address/logic/commands/DeletePatientCommand.java
src/main/java/seedu/address/logic/commands/EditDentistCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/EditDentistCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/commands/AddCommandTest.java

Identify a dentist using Dentist ID and edit at least one of any of its fields.

Branch edit dentist command

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddTreatmentCommand.java
src/main/java/seedu/address/logic/parser/AddTreatmentCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/ReadOnlyAddressBook.java
src/main/java/seedu/address/model/treatment/Treatment.java
src/main/java/seedu/address/model/treatment/TreatmentCost.java
src/main/java/seedu/address/model/treatment/TreatmentName.java
src/main/java/seedu/address/model/treatment/TreatmentTime.java
src/main/java/seedu/address/model/treatment/UniqueTreatmentList.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedTreatment.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/model/AddressBookTest.java

TODO:
- update UG and DG as this is a "new feature"
- add in more stringent checks into users data entry
- Add in more unit tests

Add in add-treatment command

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
src/main/java/seedu/address/logic/commands/FilterAppointmentCommand.java
src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/DeleteAppointmentCommandParser.java
src/main/java/seedu/address/logic/parser/FilterAppointmentCommandParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/appointments/Appointment.java
src/main/java/seedu/address/model/appointments/AppointmentNotFoundException.java
src/main/java/seedu/address/model/appointments/AppointmentTime.java
src/main/java/seedu/address/model/appointments/UniqueAppointmentList.java
src/main/java/seedu/address/model/treatment/TreatmentName.java
src/main/java/seedu/address/model/treatment/TreatmentTime.java
src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/AddDentistCommandTest.java

- Appointment now only needs to take in treatment to get both the treatment and duration of the appointment.
- Add in delete-appointment command. Appointment is deleted using appointment ID.
- Add in filter-appointment command. Appointments can now be filtered by dentists using dentist IDs.

Add in new appointment features

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/DeleteTreatmentCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/DeleteTreatmentCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/AddDentistCommandTest.java
src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
src/test/java/seedu/address/logic/commands/AddTreatmentCommandTest.java

- delete function would remove treatment by name only
- name must be an exact match

Add in delete function for treatment class

---

src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
src/main/java/seedu/address/logic/commands/FilterAppointmentCommand.java
src/main/java/seedu/address/logic/parser/FilterAppointmentCommandParser.java

Now, appointments can be filtered by either dentist ID or patient ID.

Update filter-appointment to filter by patient ID

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/EditPatientCommand.java
src/main/java/seedu/address/model/util/SampleDataUtil.java

- Add in edit-patient into UG
- Add in warnings about editing/adding treatments into UG
- Add in treatment checks into edit-patient command

Edit patient docs

---

src/main/java/seedu/address/model/util/SampleDataUtil.java

- previous specialization resulted in a illegal argument exception

critical bug fix: Updated sample data for dentist specialization

---

src/main/java/seedu/address/logic/commands/AddPatientCommand.java
src/main/java/seedu/address/logic/commands/AddTreatmentCommand.java
src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/person/UniquePatientList.java
src/main/java/seedu/address/model/person/dentist/UniqueDentistList.java
src/main/java/seedu/address/model/person/exceptions/DentistNotFoundException.java
src/main/java/seedu/address/model/person/exceptions/PatientNotFoundException.java
src/main/java/seedu/address/model/person/exceptions/TreatmentNotFoundException.java
src/main/java/seedu/address/model/treatment/Treatment.java
src/main/java/seedu/address/model/treatment/UniqueTreatmentList.java
src/main/java/seedu/address/storage/JsonAdaptedPatient.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

- fix some typos in comments
- Add in Dentist, Patient, Treatment not found exceptions
- remove AB3 add command from AB parser
- Update Hashcode function of AB

Minor Tweaks and fixes

---

src/main/java/seedu/address/storage/QuickNotesStorage.java
src/main/java/seedu/address/ui/QuickNotes.java
src/test/java/seedu/address/storage/QuickNotesStorageTest.java

* Abstract out data storage commands for `QuickNotes` into `QuickNotesStorage`
* Create `QuickNotesStorageTest` to implement JUnit test cases
`QuickNotes` should only be handling UI-related functionality.

Abstract out Storage commands for QuickNotes into separate class

---

build.gradle
src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
src/test/java/seedu/address/logic/commands/ListAppointmentCommandTest.java
src/test/java/seedu/address/logic/parser/DeleteAppointmentCommandParserTest.java
src/test/java/seedu/address/testutil/AppointmentBuilder.java
src/test/java/seedu/address/testutil/TypicalAppointments.java

- Update AddAppointmentCommandTest
- Add ListAppointmentCommandTest, DeleteAppointmentCommandTest and DeleteAppointmentCommandParserTest

Add more tests for appointment features

---

docs/UserGuide.md

Made changes to user guide according to changes requested

Add user guide updates

---

src/main/java/seedu/address/model/person/Name.java
src/test/java/seedu/address/model/person/NameTest.java

- only alphabets are accepted 
- no empty names are allowed
- spaces between names are allowed

Update Names regrex

---

docs/UserGuide.md

Changes made:
- Add Numbering to all headers and subheaders
- Standardized structure in each subheaders
- Standardized phrasing of content for similar commands, such as `search-patient` and `search-dentist`
- Standardized formatting of TIPS and INFO components

User Guide Standardization (3 Nov 2023)

---

src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/ListTreatmentCommand.java
src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
src/main/java/seedu/address/logic/parser/AddTreatmentCommandParser.java
src/main/java/seedu/address/model/person/Name.java
src/test/java/seedu/address/model/person/PersonTest.java

- #197  fixed
- #189 fixed. Now, all ID's would start from 1 when the clear command has been entered
- #180 #165 fixed. Comma replaced with full stop
- #175 fixed. 
- #202 fixed for patients and treatments. Dentist fix would be in another pr

Various bug fixes

---

src/main/java/seedu/address/logic/commands/EditDentistCommand.java
src/main/java/seedu/address/logic/commands/EditPatientCommand.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

- fixed test case errors for edit patient and edit dentist

Edit test case fix

---

src/main/java/seedu/address/logic/commands/AddDentistCommand.java
src/main/java/seedu/address/model/person/dentist/Dentist.java
src/test/java/seedu/address/logic/parser/AddDentistCommandParserTest.java
src/test/java/seedu/address/model/person/dentists/DentistTest.java

Added test cases in files `AddDentistCommandParserTest.java` and `DentistTest.java`

AddDentistCommandParser.java and Dentist.java tests

---

src/test/data/JsonSerializableAddressBookTest/duplicatePatientAddressBook.json
src/test/data/JsonSerializableAddressBookTest/duplicateTreatmentAddressBook.json
src/test/data/JsonSerializableAddressBookTest/invalidPatientAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalAppointmentsAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPatientsAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalTreatmentsAddressBook.json
src/test/java/seedu/address/model/person/UniquePatientListTest.java
src/test/java/seedu/address/model/person/patients/PatientTest.java
src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
src/test/java/seedu/address/testutil/TypicalPatients.java

- Increase unit testing to `JsonSerializableAddressBook` to increase coverage
- Add unit testing for `UniquePatientList`

Add unit testing

---

src/main/java/seedu/address/logic/commands/ListTreatmentCommand.java
src/test/java/seedu/address/logic/commands/ListTreatmentCommandTest.java
src/test/java/seedu/address/model/person/BirthdateTest.java
src/test/java/seedu/address/model/person/GenderTest.java
src/test/java/seedu/address/model/person/SpecializationTest.java
src/test/java/seedu/address/model/person/YoeTest.java

- remove full stop for list-treatment 
- Add unit tests for patient and dentist input fields

Added some unit tests and remove full stop

---

docs/DeveloperGuide.md

- Fix minor naming issues for patients section
- Add in a couple of feature enhancements

 DG updates

---

docs/DeveloperGuide.md

Update User Stories to match latest version of ToothTracker

DG - Update User Stories

---

docs/UserGuide.md

Add in delete-treatment warning into UG

---

docs/UserGuide.md

Fix typos in fields summary
